from __future__ import annotations

from PyQt6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QPushButton,
    QScrollArea,
    QSpinBox,
    QTabWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from ....core.i18n import tm
from ...widgets import FileSelectorWidget


def _create_misc_subtab(self):
    """기타 서브탭: 양식, 비교, 서명, 복호화, 첨부파일"""
    widget = QWidget()
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    content = QWidget()
    layout = QVBoxLayout(content)
    layout.setSpacing(12)

    # 양식 작성
    grp_form = QGroupBox(tm.get("grp_form"))
    l_form = QVBoxLayout(grp_form)
    self.sel_form = FileSelectorWidget()
    self.sel_form.pathChanged.connect(self._update_preview)
    l_form.addWidget(self.sel_form)
    self.form_fields_list = QListWidget()
    self.form_fields_list.setMaximumHeight(80)
    self.form_fields_list.setToolTip(tm.get("tooltip_form_list"))
    self.form_fields_list.itemDoubleClicked.connect(self._edit_form_field)
    l_form.addWidget(self.form_fields_list)
    btn_form_layout = QHBoxLayout()
    b_detect = QPushButton(tm.get("btn_detect_fields"))
    b_detect.clicked.connect(self.action_detect_fields)
    btn_form_layout.addWidget(b_detect)
    b_fill = QPushButton(tm.get("btn_save_form"))
    b_fill.setObjectName("actionBtn")
    b_fill.clicked.connect(self.action_fill_form)
    btn_form_layout.addWidget(b_fill)
    l_form.addLayout(btn_form_layout)
    layout.addWidget(grp_form)

    # PDF 비교
    grp_compare = QGroupBox(tm.get("grp_compare"))
    l_compare = QVBoxLayout(grp_compare)
    l_compare.addWidget(QLabel(tm.get("lbl_file_1")))
    self.sel_compare1 = FileSelectorWidget()
    l_compare.addWidget(self.sel_compare1)
    l_compare.addWidget(QLabel(tm.get("lbl_file_2")))
    self.sel_compare2 = FileSelectorWidget()
    l_compare.addWidget(self.sel_compare2)
    self.chk_compare_visual = QCheckBox(tm.get("chk_compare_visual_diff"))
    self.chk_compare_visual.setChecked(False)
    l_compare.addWidget(self.chk_compare_visual)
    b_compare = QPushButton(tm.get("btn_compare_pdf"))
    b_compare.setToolTip(tm.get("tooltip_compare"))
    b_compare.clicked.connect(self.action_compare_pdfs)
    l_compare.addWidget(b_compare)
    layout.addWidget(grp_compare)

    # 전자 서명
    grp_sig = QGroupBox(tm.get("grp_sig"))
    l_sig = QVBoxLayout(grp_sig)
    l_sig.addWidget(QLabel(tm.get("lbl_target_pdf")))
    self.sel_sig_pdf = FileSelectorWidget()
    self.sel_sig_pdf.pathChanged.connect(self._update_preview)
    l_sig.addWidget(self.sel_sig_pdf)
    l_sig.addWidget(QLabel(tm.get("lbl_sig_img")))
    self.sel_sig_img = FileSelectorWidget()
    self.sel_sig_img.drop_zone.accept_extensions = ['.png', '.jpg', '.jpeg']
    l_sig.addWidget(self.sel_sig_img)
    sig_opts = QHBoxLayout()
    sig_opts.addWidget(QLabel(tm.get("lbl_position")))
    self.cmb_sig_pos = QComboBox()
    sig_positions = [
        (tm.get("pos_bottom_right"), "bottom_right"),
        (tm.get("pos_bottom_left"), "bottom_left"),
        (tm.get("pos_top_right"), "top_right"),
        (tm.get("pos_top_left"), "top_left"),
    ]
    for label, value in sig_positions:
        self.cmb_sig_pos.addItem(label, value)
    sig_opts.addWidget(self.cmb_sig_pos)
    sig_opts.addWidget(QLabel(tm.get("tab_page") + ":"))
    self.spn_sig_page = QSpinBox()
    self.spn_sig_page.setRange(0, 9999)
    self.spn_sig_page.setValue(0)
    self.spn_sig_page.setSpecialValueText(tm.get("label_last_page"))
    self.spn_sig_page.setToolTip(tm.get("tooltip_sig_pos"))
    sig_opts.addWidget(self.spn_sig_page)
    sig_opts.addStretch()
    l_sig.addLayout(sig_opts)
    b_sig = QPushButton(tm.get("btn_insert_sig"))
    b_sig.clicked.connect(self.action_insert_signature)
    l_sig.addWidget(b_sig)
    layout.addWidget(grp_sig)

    # 프리핸드 서명
    grp_freehand = QGroupBox(tm.get("grp_freehand_sig"))
    l_freehand = QVBoxLayout(grp_freehand)
    self.sel_freehand_pdf = FileSelectorWidget()
    self.sel_freehand_pdf.pathChanged.connect(self._update_preview)
    l_freehand.addWidget(self.sel_freehand_pdf)
    freehand_opts = QHBoxLayout()
    freehand_opts.addWidget(QLabel(tm.get("tab_page") + ":"))
    self.spn_freehand_page = QSpinBox()
    self.spn_freehand_page.setRange(0, 9999)
    self.spn_freehand_page.setValue(0)
    self.spn_freehand_page.setSpecialValueText(tm.get("label_last_page"))
    freehand_opts.addWidget(self.spn_freehand_page)
    freehand_opts.addWidget(QLabel(tm.get("lbl_line_width")))
    self.spn_freehand_width = QSpinBox()
    self.spn_freehand_width.setRange(1, 20)
    self.spn_freehand_width.setValue(2)
    freehand_opts.addWidget(self.spn_freehand_width)
    freehand_opts.addWidget(QLabel(tm.get("lbl_color")))
    self.cmb_freehand_color = QComboBox()
    freehand_colors = [
        (tm.get("color_black"), (0, 0, 0)),
        (tm.get("color_blue"), (0, 0, 1)),
        (tm.get("color_red"), (1, 0, 0)),
    ]
    for label, value in freehand_colors:
        self.cmb_freehand_color.addItem(label, value)
    freehand_opts.addWidget(self.cmb_freehand_color)
    freehand_opts.addStretch()
    l_freehand.addLayout(freehand_opts)
    l_freehand.addWidget(QLabel(tm.get("lbl_freehand_guide")))
    self.txt_freehand_strokes = QLineEdit()
    self.txt_freehand_strokes.setPlaceholderText(tm.get("ph_freehand_strokes"))
    l_freehand.addWidget(self.txt_freehand_strokes)
    b_freehand = QPushButton(tm.get("btn_add_freehand_sig"))
    b_freehand.setObjectName("actionBtn")
    b_freehand.clicked.connect(self.action_add_freehand_signature)
    l_freehand.addWidget(b_freehand)
    layout.addWidget(grp_freehand)

    # PDF 복호화
    grp_decrypt = QGroupBox(tm.get("grp_decrypt"))
    l_decrypt = QVBoxLayout(grp_decrypt)
    self.sel_decrypt = FileSelectorWidget()
    self.sel_decrypt.pathChanged.connect(self._update_preview)
    l_decrypt.addWidget(self.sel_decrypt)
    decrypt_opts = QHBoxLayout()
    decrypt_opts.addWidget(QLabel(tm.get("lbl_pw")))
    self.inp_decrypt_pw = QLineEdit()
    self.inp_decrypt_pw.setEchoMode(QLineEdit.EchoMode.Password)
    self.inp_decrypt_pw.setPlaceholderText(tm.get("ph_decrypt_pw"))
    decrypt_opts.addWidget(self.inp_decrypt_pw)
    l_decrypt.addLayout(decrypt_opts)
    b_decrypt = QPushButton(tm.get("btn_decrypt"))
    b_decrypt.setToolTip(tm.get("tooltip_decrypt"))
    b_decrypt.clicked.connect(self.action_decrypt_pdf)
    l_decrypt.addWidget(b_decrypt)
    layout.addWidget(grp_decrypt)

    # 첨부 파일 관리
    grp_attach = QGroupBox(tm.get("grp_attach"))
    l_attach = QVBoxLayout(grp_attach)
    self.sel_attach = FileSelectorWidget()
    self.sel_attach.pathChanged.connect(self._update_preview)
    l_attach.addWidget(self.sel_attach)
    attach_btns = QHBoxLayout()
    b_list_attach = QPushButton(tm.get("btn_list_attach"))
    b_list_attach.clicked.connect(self.action_list_attachments)
    attach_btns.addWidget(b_list_attach)
    b_add_attach = QPushButton(tm.get("btn_add_attach"))
    b_add_attach.clicked.connect(self.action_add_attachment)
    attach_btns.addWidget(b_add_attach)
    b_extract_attach = QPushButton(tm.get("btn_extract_attach"))
    b_extract_attach.clicked.connect(self.action_extract_attachments)
    attach_btns.addWidget(b_extract_attach)
    l_attach.addLayout(attach_btns)
    layout.addWidget(grp_attach)

    # v4.5: 다른 PDF에서 페이지 복사
    grp_copy_page = QGroupBox(tm.get("grp_copy_page"))
    l_copy = QVBoxLayout(grp_copy_page)
    l_copy.addWidget(QLabel(tm.get("lbl_target_pdf")))
    self.sel_copy_target = FileSelectorWidget()
    self.sel_copy_target.pathChanged.connect(self._update_preview)
    l_copy.addWidget(self.sel_copy_target)
    l_copy.addWidget(QLabel(tm.get("lbl_source_pdf")))
    self.sel_copy_source = FileSelectorWidget()
    l_copy.addWidget(self.sel_copy_source)
    copy_opts = QHBoxLayout()
    copy_opts.addWidget(QLabel(tm.get("lbl_copy_pages")))
    self.txt_copy_pages = QLineEdit()
    self.txt_copy_pages.setPlaceholderText(tm.get("ph_copy_pages"))
    copy_opts.addWidget(self.txt_copy_pages)
    copy_opts.addWidget(QLabel(tm.get("lbl_insert_pos")))
    self.spn_copy_insert = QSpinBox()
    self.spn_copy_insert.setRange(-1, 9999)
    self.spn_copy_insert.setValue(-1)
    self.spn_copy_insert.setToolTip(tm.get("tooltip_insert_pos"))
    copy_opts.addWidget(self.spn_copy_insert)
    copy_opts.addStretch()
    l_copy.addLayout(copy_opts)
    b_copy_pages = QPushButton(tm.get("btn_copy_pages"))
    b_copy_pages.setObjectName("actionBtn")
    b_copy_pages.clicked.connect(self.action_copy_pages)
    l_copy.addWidget(b_copy_pages)
    layout.addWidget(grp_copy_page)

    # v4.5.3: 페이지 교체 (F-07 UI 노출)
    grp_replace = QGroupBox(tm.get("grp_replace_page"))
    l_replace = QVBoxLayout(grp_replace)
    l_replace.addWidget(QLabel(tm.get("lbl_target_pdf")))
    self.sel_replace_target = FileSelectorWidget()
    self.sel_replace_target.pathChanged.connect(self._update_preview)
    l_replace.addWidget(self.sel_replace_target)
    l_replace.addWidget(QLabel(tm.get("lbl_source_pdf")))
    self.sel_replace_source = FileSelectorWidget()
    l_replace.addWidget(self.sel_replace_source)
    replace_opts = QHBoxLayout()
    replace_opts.addWidget(QLabel(tm.get("lbl_replace_target_page")))
    self.spn_replace_target_page = QSpinBox()
    self.spn_replace_target_page.setRange(1, 9999)
    self.spn_replace_target_page.setValue(1)
    replace_opts.addWidget(self.spn_replace_target_page)
    replace_opts.addWidget(QLabel(tm.get("lbl_replace_source_page")))
    self.spn_replace_source_page = QSpinBox()
    self.spn_replace_source_page.setRange(1, 9999)
    self.spn_replace_source_page.setValue(1)
    replace_opts.addWidget(self.spn_replace_source_page)
    replace_opts.addStretch()
    l_replace.addLayout(replace_opts)
    b_replace = QPushButton(tm.get("btn_replace_page"))
    b_replace.setObjectName("actionBtn")
    b_replace.clicked.connect(self.action_replace_page)
    l_replace.addWidget(b_replace)
    layout.addWidget(grp_replace)

    # v4.5.3: 북마크 설정 (F-07 UI 노출)
    grp_set_bookmarks = QGroupBox(tm.get("grp_set_bookmarks"))
    l_set_bookmarks = QVBoxLayout(grp_set_bookmarks)
    self.sel_set_bookmarks = FileSelectorWidget()
    self.sel_set_bookmarks.pathChanged.connect(self._update_preview)
    l_set_bookmarks.addWidget(self.sel_set_bookmarks)
    l_set_bookmarks.addWidget(QLabel(tm.get("lbl_set_bookmarks_guide")))
    self.txt_set_bookmarks = QTextEdit()
    self.txt_set_bookmarks.setPlaceholderText(tm.get("ph_set_bookmarks"))
    self.txt_set_bookmarks.setMinimumHeight(90)
    l_set_bookmarks.addWidget(self.txt_set_bookmarks)
    b_set_bookmarks = QPushButton(tm.get("btn_set_bookmarks"))
    b_set_bookmarks.setObjectName("actionBtn")
    b_set_bookmarks.clicked.connect(self.action_set_bookmarks)
    l_set_bookmarks.addWidget(b_set_bookmarks)
    layout.addWidget(grp_set_bookmarks)

    # v4.5.3: 기본 주석 추가 (F-07 UI 노출)
    grp_add_annotation = QGroupBox(tm.get("grp_add_annotation_basic"))
    l_add_annotation = QVBoxLayout(grp_add_annotation)
    self.sel_add_annot = FileSelectorWidget()
    self.sel_add_annot.pathChanged.connect(self._update_preview)
    l_add_annotation.addWidget(self.sel_add_annot)
    annot_opts = QHBoxLayout()
    annot_opts.addWidget(QLabel(tm.get("tab_page") + ":"))
    self.spn_add_annot_page = QSpinBox()
    self.spn_add_annot_page.setRange(1, 9999)
    self.spn_add_annot_page.setValue(1)
    annot_opts.addWidget(self.spn_add_annot_page)
    annot_opts.addWidget(QLabel(tm.get("lbl_annotation_type")))
    self.cmb_add_annot_type = QComboBox()
    self.cmb_add_annot_type.addItem(tm.get("annot_type_text"), "text")
    self.cmb_add_annot_type.addItem(tm.get("annot_type_freetext"), "freetext")
    annot_opts.addWidget(self.cmb_add_annot_type)
    annot_opts.addStretch()
    l_add_annotation.addLayout(annot_opts)
    l_add_annotation.addWidget(QLabel(tm.get("lbl_annotation_text")))
    self.txt_add_annot_text = QLineEdit()
    self.txt_add_annot_text.setPlaceholderText(tm.get("ph_annotation_text"))
    l_add_annotation.addWidget(self.txt_add_annot_text)
    l_add_annotation.addWidget(QLabel(tm.get("lbl_annotation_point")))
    self.txt_add_annot_point = QLineEdit()
    self.txt_add_annot_point.setPlaceholderText(tm.get("ph_annotation_point"))
    l_add_annotation.addWidget(self.txt_add_annot_point)
    l_add_annotation.addWidget(QLabel(tm.get("lbl_annotation_rect")))
    self.txt_add_annot_rect = QLineEdit()
    self.txt_add_annot_rect.setPlaceholderText(tm.get("ph_annotation_rect"))
    l_add_annotation.addWidget(self.txt_add_annot_rect)
    b_add_annotation = QPushButton(tm.get("btn_add_annotation_basic"))
    b_add_annotation.setObjectName("actionBtn")
    b_add_annotation.clicked.connect(self.action_add_annotation_basic)
    l_add_annotation.addWidget(b_add_annotation)
    layout.addWidget(grp_add_annotation)

    layout.addStretch()
    scroll.setWidget(content)
    main_layout = QVBoxLayout(widget)
    main_layout.setContentsMargins(0, 0, 0, 0)
    main_layout.addWidget(scroll)
    return widget
