from __future__ import annotations


MODE_TO_HANDLER = {
    "add_annotation": "add_annotation",
    "add_attachment": "add_attachment",
    "add_background": "add_background",
    "add_freehand_signature": "add_freehand_signature",
    "add_ink_annotation": "add_ink_annotation",
    "add_link": "add_link",
    "add_page_numbers": "add_page_numbers",
    "add_stamp": "add_stamp",
    "add_sticky_note": "add_sticky_note",
    "add_text_markup": "add_text_markup",
    "ai_ask_question": "ai_ask_question",
    "ai_extract_keywords": "ai_extract_keywords",
    "ai_summarize": "ai_summarize",
    "batch": "batch",
    "compare_pdfs": "compare_pdfs",
    "compress": "compress",
    "convert_to_img": "convert_to_img",
    "copy_page_between_docs": "copy_page_between_docs",
    "crop_pdf": "crop_pdf",
    "decrypt_pdf": "decrypt_pdf",
    "delete_pages": "delete_pages",
    "draw_shapes": "draw_shapes",
    "duplicate_page": "duplicate_page",
    "extract_attachments": "extract_attachments",
    "extract_images": "extract_images",
    "extract_links": "extract_links",
    "extract_markdown": "extract_markdown",
    "extract_tables": "extract_tables",
    "extract_text": "extract_text",
    "fill_form": "fill_form",
    "get_bookmarks": "get_bookmarks",
    "get_form_fields": "get_form_fields",
    "get_pdf_info": "get_pdf_info",
    "highlight_text": "highlight_text",
    "image_watermark": "image_watermark",
    "images_to_pdf": "images_to_pdf",
    "insert_blank_page": "insert_blank_page",
    "insert_signature": "insert_signature",
    "insert_textbox": "insert_textbox",
    "list_annotations": "list_annotations",
    "list_attachments": "list_attachments",
    "merge": "merge",
    "metadata_update": "metadata_update",
    "protect": "protect",
    "redact_text": "redact_text",
    "remove_annotations": "remove_annotations",
    "reorder": "reorder",
    "replace_page": "replace_page",
    "resize_pages": "resize_pages",
    "reverse_pages": "reverse_pages",
    "rotate": "rotate",
    "search_text": "search_text",
    "set_bookmarks": "set_bookmarks",
    "split": "split",
    "split_by_pages": "split_by_pages",
    "watermark": "watermark",
}


def get_handler_method_name(mode: str) -> str | None:
    return MODE_TO_HANDLER.get(mode)
